git:
  pagers:
    - pager: delta --paging=never --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

gui:
  showIcons: true
  theme:
    activeBorderColor:
      - '#8bd5ca'
      - bold
    inactiveBorderColor:
      - '#a5adcb'
    optionsTextColor:
      - '#8aadf4'
    selectedLineBgColor:
      - '#363a4f'
    cherryPickedCommitBgColor:
      - '#494d64'
    cherryPickedCommitFgColor:
      - '#8bd5ca'
    unstagedChangesColor:
      - '#ed8796'
    defaultFgColor:
      - '#cad3f5'
    searchingActiveBorderColor:
      - '#eed49f'

  authorColors:
    '*': '#b7bdf8'

os:
  editInTerminal: false

  # 'edit' is used when you press 'e' on a file
  edit: >-
    zellij action go-to-tab 1 &&
    zellij action move-focus left &&
    zellij action move-focus up &&
    sleep 0.05 &&
    zellij action write 27 &&
    zellij action write-chars ":open {{filename}}" &&
    zellij action write 13

  # 'editAtLine' is used when you press 'e' inside a diff/hunk
  editAtLine: >-
    zellij action go-to-tab 1 &&
    zellij action move-focus left &&
    zellij action move-focus up &&
    sleep 0.05 &&
    zellij action write 27 &&
    zellij action write-chars ":open {{filename}}:{{line}}" &&
    zellij action write 13

  # 'open' is used for non-text files (images, pdfs, etc)
  open: xdg-open {{filename}} >/dev/null 2>&1 &
