[toolchain]
channel = "nightly"
components = [ "rust-src", "rust-analyzer", "rustc-codegen-cranelift", "miri", "llvm-tools", "rust-docs-json" ]
targets = [
    "wasm32-unknown-unknown",
    "wasm32-wasi",
    "x86_64-pc-windows-gnu",
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl"
  ]
profile = "default"
