[pyprland]
plugins = [
  "scratchpads",
  "magnify",
  "expose",
  "shortcuts_menu",
  "toggle_special",
]

[scratchpads.term]
command = "kitty --class terminal-dropterm"
class = "terminal-dropterm"
animation = "fromTop"
unfocus = "hide"
excludes = "*"
lazy = true
multi = false
size = "75% 60%"
max_size = "1920px 100%"
margin = 50

[scratchpads.volume]
command = "pavucontrol"
animation = "fromLeft"
class = "org.pulseaudio.pavucontrol"
size = "40% 70%"
unfocus = "hide"
excludes = "*"
lazy = true
margin = 90
multi = false

[shortcuts_menu.entries]

"Color picker" = [
    {name="format", options=["hex", "rgb", "hsv", "hsl", "cmyk"]},
    "sleep 0.2; hyprpicker --format [format] -a" # sleep to let the menu close before the picker opens
]
